const fs = require('fs')
const path = require('path')

let required

if (!process.env.TAILWIND_FLAVOUR || process.env.TAILWIND_FLAVOUR === 'tailwind') {
  required = [
    'lists',
    'appearance',
    'backgroundAttachment',
    'backgroundColors',
    'backgroundPosition',
    'backgroundRepeat',
    'backgroundSize',
    'borderColors',
    'borderRadius',
    'borderStyle',
    'borderWidths',
    'cursor',
    'display',
    'flexbox',
    'float',
    'fonts',
    'fontWeights',
    'height',
    'leading',
    'margin',
    'maxHeight',
    'maxWidth',
    'minHeight',
    'minWidth',
    'negativeMargin',
    'opacity',
    'overflow',
    'padding',
    'pointerEvents',
    'position',
    'resize',
    'shadows',
    'svgFill',
    'svgStroke',
    'textAlign',
    'textColors',
    'textSizes',
    'textStyle',
    'tracking',
    'userSelect',
    'verticalAlign',
    'visibility',
    'whitespace',
    'width',
    'zIndex',
  ]
} else if (process.env.TAILWIND_FLAVOUR === 'tachyons') {
  required = [
    'lists',
    'appearance',
    'aspectRatios',
    'rotate',
    'boxSizing',
    'backgroundAttachment',
    'backgroundColors',
    'backgroundForegroundColors',
    'backgroundPosition',
    'backgroundRepeat',
    'backgroundSize',
    'borders',
    'borderColors',
    'borderRadius',
    'borderStyle',
    'borderWidths',
    'cursor',
    'display',
    'flexbox',
    'float',
    'fonts',
    'fontWeights',
    'height',
    'leading',
    'margin',
    'maxHeight',
    'maxWidth',
    'minHeight',
    'minWidth',
    'negativeMargin',
    'opacity',
    'overflow',
    'padding',
    'pointerEvents',
    'position',
    'resize',
    'shadows',
    'svgFill',
    'svgStroke',
    'textAlign',
    'textColors',
    'textSizes',
    'textStyle',
    'tracking',
    'userSelect',
    'verticalAlign',
    'visibility',
    'whitespace',
    'width',
    'zIndex',
    'outline',
    'cms',
    'typography',
    'debug',
    'interactive',
    'reset',
    'stripes',
  ]
}

export default required.map(x => {
  let gen = path.resolve(`${__dirname}/generators/${x}.js`)
  let libGen = path.resolve(`${__dirname}/generators/${x}.${process.env.TAILWIND_FLAVOUR}.js`)
  let generator = fs.existsSync(libGen) ? require(libGen) : require(gen)

  return {
    name: x,
    generator: generator.default ? generator.default : generator,
  }
})
